services:
  - type: web
    name: order-service
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput && gunicorn order_service.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: order_service.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: OIDC_RP_CLIENT_ID
        sync: false
      - key: OIDC_RP_CLIENT_SECRET
        sync: false
      - key: AFRICASTALKING_USERNAME
        value: sandbox
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: order-service-twcc.onrender.com
