services:
  - type: web
    name: order-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./entrypoint.sh
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: OIDC_RP_CLIENT_ID
        sync: false
      - key: OIDC_RP_CLIENT_SECRET
        sync: false
      - key: AFRICASTALKING_USERNAME
        value: sandbox
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: order-service-twcc.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: MIGRATION_SECRET_TOKEN
        sync: false 
