services:
  - type: web
    name: order-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn order_service.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: order_service.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: AFRICASTALKING_USERNAME
        sync: false
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: OIDC_RP_CLIENT_ID
        sync: false
      - key: OIDC_RP_CLIENT_SECRET
        sync: false

